name: Playwright Tests

on:
  push:
    branches:
      - main  # Kích hoạt khi có push vào nhánh 'main'
  pull_request:
    branches:
      - main  # Kích hoạt khi có pull request vào nhánh 'main'
  workflow_dispatch:  # Kích hoạt thủ công (manual trigger)

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'lts'

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright Tests
      run: npx playwright test
