name: CICD HCM

on:
  push:
    branches:
      - main  # Chạy khi có push lên nhánh main
  pull_request:
    branches:
      - main  # Chạy khi có PR vào nhánh main

jobs:
  Ho_Thom:
    timeout-minutes: 60
    runs-on: [self-hosted, windows]  # Sử dụng runner tự host trên máy Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright and browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test tests/employee-set-wkm/employee-creat-wkm-onsite.spec.ts          

      - name: Upload HTML Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: playwright-report/  # Đảm bảo đúng đường dẫn báo cáo
