name: CICD HCM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Ho_Thom:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright and browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload HTML Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: test-results/html-report  # Đường dẫn đến thư mục chứa báo cáo HTML

      - name: Upload JSON Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: playwright-json-report
          path: test-results/json-report  # Đường dẫn đến thư mục chứa báo cáo JSON
